wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.11
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702409917.644493
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.9.11
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
